name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          cache: maven

      - run: mvn --batch-mode verify

      - uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: site/target/site/jacoco-aggregate/jacoco.csv
          generate-branches-badge: true
          generate-coverage-endpoint: true
          generate-branches-endpoint: true
          generate-summary: true

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
