name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          cache: maven

      - run: mvn --batch-mode verify

      - uses: codecov/codecov-action@v3
        with:
          files: core/target/site/jacoco/jacoco.xml,junit/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
