name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - run: |
          sudo gem install hoc
          hoc -h

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          cache: maven

      - run: ./mvnw --batch-mode verify

      - uses: codecov/codecov-action@v3
        with:
          file: site/target/site/jacoco-aggregate/jacoco.xml
          fail_ci_if_error: true
